In [5]:
from dpm.utils import gradient, hessian, newton_step
import torch

In [6]:
x = torch.rand(4)
x.requires_grad = True
x

tensor([0.2491, 0.0746, 0.3974, 0.8919], requires_grad=True)

In [7]:
theta = torch.rand(4)
theta.requires_grad = True
theta

tensor([0.2414, 0.3916, 0.5617, 0.8370], requires_grad=True)

In [8]:
l = theta.dot(x) * theta.dot(theta)
l

tensor(1.3003, grad_fn=<MulBackward0>)

In [9]:
g = gradient(l, (x, theta))
print(g)
g = gradient(l, theta)
print(g)
g = gradient(l, x)
print(g)

(tensor([0.2964, 0.4808, 0.6896, 1.0277], grad_fn=<MulBackward0>), tensor([0.8172, 0.9211, 1.6777, 2.8681], grad_fn=<AddBackward0>))
tensor([0.8172, 0.9211, 1.6777, 2.8681], grad_fn=<AddBackward0>)
tensor([0.2964, 0.4808, 0.6896, 1.0277], grad_fn=<MulBackward0>)


In [10]:
h = hessian(l, theta)
h

tensor([[2.3588, 0.2311, 0.4717, 0.8477],
        [0.2311, 2.2352, 0.3951, 0.8235],
        [0.4717, 0.3951, 3.0111, 1.6672],
        [0.8477, 0.8235, 1.6672, 5.1046]], grad_fn=<StackBackward>)

In [11]:
Hinv = torch.inverse(h)
Hinv.shape, g.shape

(torch.Size([4, 4]), torch.Size([4]))

In [12]:
ns = newton_step(l, theta)
ns

tensor([-0.1207, -0.1958, -0.2808, -0.4185], grad_fn=<NegBackward>)

In [19]:
ns = newton_step(l, theta, use_pinv=True)
ns

tensor([-0.1207, -0.1958, -0.2808, -0.4185], grad_fn=<NegBackward>)

In [13]:
H, g = hessian(l, theta, True)

In [14]:
print(H)
print(g)

tensor([[2.3588, 0.2311, 0.4717, 0.8477],
        [0.2311, 2.2352, 0.3951, 0.8235],
        [0.4717, 0.3951, 3.0111, 1.6672],
        [0.8477, 0.8235, 1.6672, 5.1046]], grad_fn=<StackBackward>)
tensor([0.8172, 0.9211, 1.6777, 2.8681], grad_fn=<AddBackward0>)


In [18]:
Hinv = torch.inverse(H)
-Hinv.mv(g)

tensor([-0.1207, -0.1958, -0.2808, -0.4185], grad_fn=<NegBackward>)